name: Build and Test React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean install dependencies
        run: npm ci

      - name: Verify react-scripts is available
        run: |
          npm list react-scripts || npm install react-scripts

      - name: Build project
        run: npm run build

      - name: Start app
        run: |
          nohup npm start &
          sleep 10

      - name: Test app with curl
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [ "$STATUS" -ne 200 ]; then
            echo "App did not start correctly (status: $STATUS)"
            exit 1
          fi
