name: Build and Test React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Forcer l'installation de react-scripts si manquant
      - name: Ensure react-scripts is installed
        run: |
          if ! npm list react-scripts > /dev/null 2>&1; then
            echo "react-scripts not found, installing..."
            npm install react-scripts --save-dev
          fi

      # 5. Build du projet
      - name: Build project
        run: npm run build

      # 6. Démarrer le serveur
      - name: Start app
        run: |
          nohup npm start &
          sleep 10

      # 7. Vérifier que l'app répond
      - name: Test app with curl
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [ "$STATUS" -ne 200 ]; then
            echo "App did not start correctly (status: $STATUS)"
            exit 1
          fi
